import { PLAYER_META, ROOT_ID } from "./constants";
import { getKifPieceName, getNumericSquare, getSquareLabel } from "./model";
import type { KifuNode, MoveRecord } from "./types";

export const buildNotation = (move: Omit<MoveRecord, "notation">): string => {
  const playerMark = PLAYER_META[move.owner].mark;
  const pieceName = getKifPieceName(move.piece, move.promotedBefore);
  const source = move.drop ? "打" : move.from !== undefined ? `(${getNumericSquare(move.from)})` : "";
  const promotion = move.promotedAfter && !move.promotedBefore ? "成" : "";
  return `${playerMark}${getSquareLabel(move.to)}${pieceName}${source}${promotion}`;
};

export const downloadTextFile = (filename: string, content: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};

export const formatTimestamp = () => {
  const now = new Date();
  const pad = (value: number) => value.toString().padStart(2, "0");
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}`;
};

export const getDescendantIds = (nodes: Record<string, KifuNode>, nodeId: string): string[] => {
  const target = nodes[nodeId];
  if (!target) return [];
  return target.children.flatMap((childId) => [childId, ...getDescendantIds(nodes, childId)]);
};

export const buildKif = (nodes: Record<string, KifuNode>): string => {
  const lines: string[] = [
    "#KIF version=2.0 encoding=UTF-8",
    "# Generated by LUNA_PROTOCOL SHOGI_NODE",
    `開始日時：${new Date().toLocaleString("ja-JP")}`,
    "手合割：平手",
    "先手：SENTE",
    "後手：GOTE",
    "手数----指手---------消費時間--",
  ];

  const appendNodeLine = (node: KifuNode): void => {
    if (!node.move) return;
    lines.push(`${node.moveNumber} ${node.move.notation}`);
    if (node.comment.trim()) {
      node.comment.split(/\r?\n/).forEach((commentLine) => lines.push(`*${commentLine}`));
    }
  };

  const appendLineFrom = (startId: string): void => {
    let nodeId: string | undefined = startId;
    while (nodeId) {
      const node = nodes[nodeId];
      if (!node) break;
      appendNodeLine(node);
      node.children.slice(1).forEach((branchId) => {
        const branchNode = nodes[branchId];
        if (!branchNode) return;
        lines.push("");
        lines.push(`変化：${branchNode.moveNumber}手`);
        appendLineFrom(branchId);
      });
      nodeId = node.children[0];
    }
  };

  const root = nodes[ROOT_ID];
  if (root?.children[0]) appendLineFrom(root.children[0]);

  root?.children.slice(1).forEach((branchId) => {
    lines.push("");
    lines.push("変化：1手");
    appendLineFrom(branchId);
  });

  return `${lines.join("\n")}\n`;
};
